### ISSUE TITLE
Grade for "Checkout form page template"

### ISSUE THREAD

**Issue by juliannastepha** [juliannastepha/ecommerce-pattern-library#5]
@thomasjbradley
I've made my checkout form! I hope I did it right.

**Comment by thomasjbradley** [comment]
It seems like it didn’t leverage the pattern library enough.

I think this should be converted into a pattern:
https://github.com/juliannastepha/ecommerce-pattern-library/blob/master/checkout-form.html#L74-L101

And all the form fields should be using their appropriate  `{% pattern %}` tags.
